# GENERATED by build.rs — DO NOT EDIT
# Any changes will be overwritten on next build.
# SCHEMA_HASH ensures Rust and Python layouts stay synchronized.

import ctypes
from typing import Final

# ============================================================================
# SCHEMA_HASH - MUST match src/generated/layout.rs
# ============================================================================

SCHEMA_HASH: Final[bytes] = bytes.fromhex('37361e3c27dbcf6074ea7322542252a05fd49c4d6cb482a7fb803096bea0c096')

# ============================================================================
# Region Sizes
# ============================================================================

IMMUTABLE_SIZE: Final[int] = 67108864
APPEND_ONLY_SIZE: Final[int] = 2097152
MUTABLE_SIZE: Final[int] = 8388608
COMPUTE_SIZE: Final[int] = 268435456

HEADER_SIZE: Final[int] = 64

# ============================================================================
# Observation Ring
# ============================================================================

OBSERVATION_SLOT_COUNT: Final[int] = 150
OBSERVATION_SLOT_SIZE: Final[int] = 320
OBSERVATION_CONTENT_BYTES: Final[int] = 256
OBSERVATION_CACHE_PAD_BYTES: Final[int] = 64

# ============================================================================
# Slab Allocator Sizes
# ============================================================================

GOAL_CONTRACT_SLOTS: Final[int] = 256
GOAL_CONTRACT_BYTES: Final[int] = 3072
GOAL_STATE_SLOTS: Final[int] = 512
GOAL_STATE_BYTES: Final[int] = 1024
OBSERVATION_SLOTS: Final[int] = 150
OBSERVATION_BYTES: Final[int] = 320
ATOMIC_COUNTER_SLOTS: Final[int] = 1024
ATOMIC_COUNTER_BYTES: Final[int] = 8

# ============================================================================
# Embedding Configuration
# ============================================================================

EMBEDDING_DIM: Final[int] = 512
EMBEDDING_MAX_APPS: Final[int] = 1000
EMBEDDING_CACHE_MAX_ENTRIES: Final[int] = 1024

# ============================================================================
# Event Log Configuration
# ============================================================================

EVENT_LOG_CAPACITY_BYTES: Final[int] = 1048576
EVENT_LOG_AVG_EVENT_BYTES: Final[int] = 100
EMERGENCY_BUFFER_BYTES: Final[int] = 65536

# ============================================================================
# Timeouts
# ============================================================================

SQLITE_READY_TIMEOUT_MS: Final[int] = 5000
WRITE_LOCK_TIMEOUT_MS: Final[int] = 500
COMPUTE_REFRESH_MIN: Final[int] = 5

# ============================================================================
# Computed Offsets
# ============================================================================

# Region bases (from start of total mmap)
IMMUTABLE_BASE: Final[int] = 0
APPEND_ONLY_BASE: Final[int] = 67108864
MUTABLE_BASE: Final[int] = 69206016
COMPUTE_BASE: Final[int] = 77594624

# Within APPEND_ONLY region
OBSERVATION_RING_OFFSET: Final[int] = 64
EVENT_LOG_OFFSET: Final[int] = 48064
EMERGENCY_BUFFER_OFFSET: Final[int] = 2031616

# Within COMPUTE region
MATRIX_OFFSET: Final[int] = 0
HNSW_INDEX_OFFSET: Final[int] = 2097152
EMBEDDING_CACHE_OFFSET: Final[int] = 54525952

# ============================================================================
# ObservationSnapshot Structure (320 bytes total)
# ============================================================================

class ObservationSnapshot(ctypes.Structure):
    """Observation snapshot stored in the observation ring.

    Total size: 320 bytes (256 content + 64 cache pad).
    Layout matches Rust #[repr(C)] WorldModelScalars.
    """
    _pack_ = 1
    _fields_ = [
        # Content: 256 bytes
        ('timestamp_ns', ctypes.c_uint64),      # offset 0, size 8
        ('active_pid', ctypes.c_uint32),        # offset 8, size 4
        ('cpu_pct_bits', ctypes.c_uint32),      # offset 12, size 4 (f32 bits)
        ('memory_used_mb', ctypes.c_uint32),    # offset 16, size 4
        ('disk_free_gb_bits', ctypes.c_uint32), # offset 20, size 4 (f32 bits)
        ('network_reachable', ctypes.c_uint8),  # offset 24, size 1
        ('_reserved', ctypes.c_uint8 * 231),    # offset 25, size 231 (padding)
        # Cache pad: 64 bytes
        ('_cache_pad', ctypes.c_uint8 * 64),    # offset 256, size 64
    ]

# Verify size at import time
assert ctypes.sizeof(ObservationSnapshot) == OBSERVATION_SLOT_SIZE, \
    f"ObservationSnapshot size mismatch: {ctypes.sizeof(ObservationSnapshot)} != {OBSERVATION_SLOT_SIZE}"

# ============================================================================
# Schema Hash Verification
# ============================================================================

class NexusLayoutError(Exception):
    """Raised when Python layout does not match Rust layout."""
    pass

def verify_schema_hash(mmap_header: bytes) -> None:
    """Verify that the mmap header SCHEMA_HASH matches this layout.

    Called at Python startup after importing nexus_native.
    Raises NexusLayoutError if hashes do not match.

    Args:
        mmap_header: First 64 bytes of the mmap (header region).

    Raises:
        NexusLayoutError: If SCHEMA_HASH in header differs from this layout.
    """
    if len(mmap_header) < 32:
        raise NexusLayoutError(
            f"mmap header too short: {len(mmap_header)} bytes, expected at least 32"
        )

    # Extract SCHEMA_HASH from header (first 32 bytes)
    header_hash = mmap_header[:32]

    if header_hash != SCHEMA_HASH:
        header_hex = header_hash.hex()
        expected_hex = SCHEMA_HASH.hex()
        raise NexusLayoutError(
            f"SCHEMA_HASH mismatch\\n"
            f"  expected (from _layout.py): {expected_hex}\\n"
            f"  found (from mmap header):   {header_hex}\\n"
            f"  fix: run `cargo build` to regenerate _layout.py"
        )
